baseURL = "https://docs.setops.co/"
languageCode = "en-us"
title = "SetOps"
theme = "book"
enableEmoji = true
pygmentsUseClasses = true
enableGitInfo = true
disableKinds = ['taxonomyTerm']

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Homepage"
  url = "https://www.setops.co"
  weight = 10

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/setopsco"
  weight = 20

[[menu.after]]
  name = "API Reference"
  url = "/api/"
  weight = 30

[[menu.after]]
  name = "Support"
  url = "mailto:support@setops.co"
  weight = 40

[params]
BookSection = '/latest/user'
BookTheme = "light"
BookLogo="setops_logo.png"
BookRepo = 'https://github.com/setopsco/docs'
BookEditPath = 'edit/main'

[markup.goldmark.renderer]
unsafe = true
